---
- name: Tasks to create a cronjob to dump all PostgreSQL databases
  block:

    - name: Include tasks to get the HOME directory for the PostgreSQL user
      include_tasks: home.yml

    - name: Backup directory present
      file:
        path: "{{ postgresql_backups }}"
        state: directory
        owner: "{{ postgresql_superuser | default('postgres') }}"
        group: "{{ postgresql_superuser | default('postgres') }}"
        mode: 0700

    - name: List the PostgreSQL databases
      command: psql -Stc "SELECT datname FROM pg_database"
      args:
        chdir: "{{ postgresql_postgres_home | default('/var/lib/postgresql') }}"
      environment:
        PAGER: ""
      register: postgresql_datnames
      become: true
      become_user: "{{ postgresql_superuser | default('postgres') }}"

    - name: Generate an array of the database names
      set_fact:
        postgresql_databases: "{{ postgresql_databases | default([]) }} + [ '{{ line | trim }}' ]"
      when:
        - ( line | length > 0 )
        - ( line != " template0" )
        - ( line != " template1" )
      loop: "{{ postgresql_datnames.stdout_lines }}"
      loop_control:
        loop_var: line
        label: "{{ line | trim }}"

    - name: Debug PostgreSQL databases
      debug:
        var: postgresql_databases
        verbosity: 2

    - name: Crontab present
      cron:
        user: "{{ postgresql_superuser | default('postgres') }}"
        name: "Dump PostgreSQL databases"
        job: "{% for d in postgresql_databases %}pg_dump {{ d }} > {{ postgresql_backups | default('/var/backups/postgres') }}/{{ d }}.sql ; {% endfor %}"
        hour: "{{ postgresql_cron_hour | default('02') }}"
        minute: "{{ 59 | random }}"

  tags:
    - postgresql
...
