---
- name: PostgreSQL user present
  block:

    - name: "PostgreSQL password for {{ postgresql_user }} present"
      shell: "pwgen -n 20 1 > /root/.postgresql.{{ postgresql_user }}.passwd"
      args:
        creates: "/root/.postgresql.{{ postgresql_user }}.passwd"

    - name: "PostgreSQL password /root/.postgresql.{{ postgresql_user }}.passwd slurped"
      slurp:
        src: "/root/.postgresql.{{ postgresql_user }}.passwd"
      register: postgresql_passwd_file_b64encoded

    - name: Fact set for the PostgreSQL password
      set_fact:
        postgresql_passwd: "{{ postgresql_passwd_file_b64encoded['content'] | b64decode | trim }}"

    - name: PostgreSQL user present
      postgresql_user:
        name: "{{ postgresql_user }}"
        password: "{{ postgresql_passwd }}"
        db: "{{ postgresql_db }}"
        priv: ALL
        state: present
      become: true
      become_user: postgres

  when:
    - ( postgresql_db is defined )
    - ( postgresql_db | length > 0 )
    - ( postgresql_user is defined )
    - ( postgresql_user | length > 0 )
  tags:
    - postgresql
...
