---
- name: Create a PostgreSQL database
  block:

    # https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
    - name: Ensure that the postgresql_db variable value is sensible
      ansible.builtin.assert:
        that:
          - postgresql_db is regex("^[a-z][a-z0-9_]{1,25}$")

    - name: Add a PostgreSQL database
      community.postgresql.postgresql_db:
        name: "{{ postgresql_db }}"
        state: present
      become: true
      become_user: "{{ postgresql_superuser | default('postgres') }}"

  when:
    - ( postgresql_db is defined )
    - ( postgresql_db | length > 0 )
  tags:
    - postgresql
...
