---
- name: Add a PostgreSQL database
  postgresql_db:
    name: "{{ postgresql_db }}"
    state: present
  become: true
  become_user: postgres
  when:
    - ( postgresql_db is defined )
    - ( postgresql_db | length > 0 )
    - ( postgresql_user is defined )
    - ( postgresql_user | length > 0 )
  tags:
    - postgresql
...
