---
- name: PostgreSQL user HOME directory
  block:

    - name: Getent passwd
      ansible.builtin.getent:
        database: passwd

    - name: Debug getent_passwd
      ansible.builtin.debug:
        var: getent_passwd
        verbosity: 2

    - name: Set a variable for the HOME directory of the postgres user
      ansible.builtin.set_fact:
        postgresql_postgres_home: "{{ getent_passwd | community.general.json_query(postgresql_postgres_home_query) }}"

    - name: Debug the postgres HOME directory
      ansible.builtin.debug:
        var: postgresql_postgres_home
        verbosity: 1

  tags:
    - postgresql
...
