# Copyright 2020-2023 Chris Croome
#
# This file is part of the Webarchitects PostgreSQL Ansible role.
#
# The Webarchitects PostgreSQL Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects PostgreSQL Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects PostgreSQL Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: PostgreSQL info
  block:

    - name: Stat /usr/bin/pg_lsclusters
      ansible.builtin.stat:
        path: /usr/bin/pg_lsclusters
      register: postgresql_ps_lsclusters_check

    - name: Gather PostgreSQL info when pg_lsclusters is present
      block:

        # - name: Run pg_lsclusters -j
        #   ansible.builtin.command: pg_lsclusters -j
        #   changed_when: false
        #   check_mode: false
        #   register: postgresql_ps_lsclusters

        # - name: Set a fact for the results of pg_lsclusters -j
        #   ansible.builtin.set_fact:
        #     postgresql_lsclusters: "{{ postgresql_ps_lsclusters.stdout }}"

        # - name: Debug postgresql_ps_lsclusters
        #   ansible.builtin.debug:
        #     var: postgresql_lsclusters
        #     verbosity: 3

        - name: PostgreSQL info
          community.postgresql.postgresql_info:
            login_user: "{{ postgresql_superuser }}"
            port: "{{ postgresql_port }}"
            filter:
              - databases
              - roles
              - version
          register: postgresql_info
          become: true
          become_user: "{{ postgresql_superuser }}"

        - name: Debug PostgreSQL info
          ansible.builtin.debug:
            var: postgresql_info
            verbosity: 3

        - name: Set a fact for the existing PostgreSQL databases
          ansible.builtin.set_fact:
            postgresql_dbs_existing: "{{ postgresql_info.databases.keys() }}"

        - name: Debug xisting PostgreSQL databases
          ansible.builtin.debug:
            var: postgresql_dbs_existing

        - name: Set a fact for the existing PostgreSQL users
          ansible.builtin.set_fact:
            postgresql_users_existing: "{{ postgresql_info.roles.keys() }}"

        - name: Debug existing PostgreSQL users
          ansible.builtin.debug:
            var: postgresql_users_existing

      when: postgresql_ps_lsclusters_check.stat.exists | bool

  tags:
    - postgresql
...
