---
- name: PostgreSQL info
  block:

    - name: PostgreSQL info
      community.postgresql.postgresql_info:
        login_user: "{{ postgresql_superuser }}"
        port: "{{ postgresql_port }}"
        filter:
          - databases
          - roles
          - settings
          - tablespaces
          - version
      register: postgresql_info
      become: true
      become_user: "{{ postgresql_superuser }}"

    - name: Debug PostgreSQL info
      ansible.builtin.debug:
        var: postgresql_info
        verbosity: 3

  tags:
    - postgresql
...
