---
- name: PostgreSQL packages present
  apt:
    pkg:
      - postgresql
      - pwgen
      - python3-psycopg2
  tags:
    - postgresql

- name: PostgreSQL enabled
  service:
    name: "{{ postgresql_daemon }}"
    state: started
  tags:
    - postgresql
...
