---
- name: PostgreSQL packages present
  apt:
    pkg:
      - postgresql
      - pwgen
      - python-psycopg2
      - python3-psycopg2
  tags:
    - postgresql

- name: PostgreSQL enabled
  service:
    name: postgresql
    state: enabled
  tags:
    - postgresql
...
