---
- name: PostgreSQL packages present
  ansible.builtin.apt:
    pkg:
      - postgresql
      - pwgen
      - python3-psycopg2
  tags:
    - postgresql

- name: PostgreSQL enabled
  ansible.builtin.service:
    name: "{{ postgresql_daemon }}"
    state: started
  tags:
    - postgresql
...
