---
- name: Install PostgreSQL
  include_tasks: install.yml
  tags:
    - postgresql

- name: Create PostgreSQL database
  include_tasks: create_db.yml
  when:
    - ( postgresql_db is defined )
    - ( postgresql_db | length > 0 )
    - ( postgresql_user is defined )
    - ( postgresql_user | length > 0 )
  tags:
    - postgresql

- name: Create PostgreSQL user
  include_tasks: create_user.yml
  when:
    - ( postgresql_db is defined )
    - ( postgresql_db | length > 0 )
    - ( postgresql_user is defined )
    - ( postgresql_user | length > 0 )
  tags:
    - postgresql
...
