# Copyright 2020-2025 Chris Croome
#
# This file is part of the Webarchitects PostgreSQL Ansible role.
#
# The Webarchitects PostgreSQL Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects PostgreSQL Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects PostgreSQL Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: PostgreSQL role skipped
  ansible.builtin.debug:
    msg: "The tasks in the PostgreSQL role are not being run since the postgresql variable is not true."
  when: >-
    ( postgresql is not defined ) or
    ( not postgresql | bool )
  tags:
    - postgresql

- name: Install and configure PostgreSQL
  block:

    - name: This role only currently supports Debian Trixie, Bookworm, Bullseye and Ubuntu Jammy and Noble
      ansible.builtin.assert:
        that:
          - ansible_facts.distribution_release is regex('^bookworm|bullseye|jammy|noble|trixie$')
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Validate PostgreSQL variables
      ansible.builtin.include_tasks: validate.yml
      when: postgresql_validate | bool
      tags:
        - postgresql_validate

    - name: Include apt role local fact tasks
      ansible.builtin.include_role:
        name: apt
        tasks_from: local_facts.yml
      when: >-
        ( ansible_facts.ansible_local.dpkg.arch is not defined ) or
        ( ansible_facts.ansible_local.gpg.version is not defined ) or
        ( ansible_facts.ansible_local.bash.path is not defined )

    - name: PostgreSQL install tasks
      ansible.builtin.include_tasks: install.yml
      tags:
        - postgresql_install

    - name: PostgreSQL config tasks
      ansible.builtin.include_tasks: conf.yml
      tags:
        - postgresql_conf

    - name: PostgreSQL info tasks
      ansible.builtin.include_tasks: info.yml
      tags:
        - postgresql_info

    - name: PostgreSQL user and database present
      block:

        - name: PostgreSQL user and database present
          block:

            - name: PostgreSQL database tasks
              ansible.builtin.include_tasks: db.yml

            - name: PostgreSQL user tasks
              ansible.builtin.include_tasks: user.yml

          when:
            - postgresql_db is defined
            - postgresql_db | length > 0
            - postgresql_user is defined
            - postgresql_user | length > 0

        - name: PostgreSQL backup tasks
          ansible.builtin.include_tasks: backup.yml
          when:
            - postgresql_backups is defined
            - postgresql_backups | length > 0

      when: >-
        ( postgresql_service.skipped is not defined ) or
        ( not postgresql_service.skipped | bool )

  when:
    - postgresql is defined
    - postgresql | bool
  tags:
    - postgresql
...
