---
- name: Install PostgreSQL
  include_tasks: install.yml
  tags:
    - postgresql

- name: PostgreSQL database present
  include_tasks: db.yml
  when:
    - ( postgresql_db is defined )
    - ( postgresql_db | length > 0 )
    - ( postgresql_user is defined )
    - ( postgresql_user | length > 0 )
  tags:
    - postgresql

- name: PostgreSQL user present
  include_tasks: user.yml
  when:
    - ( postgresql_db is defined )
    - ( postgresql_db | length > 0 )
    - ( postgresql_user is defined )
    - ( postgresql_user | length > 0 )
  tags:
    - postgresql

- name: PostgreSQL dump crontab present
  include_tasks: backup.yml
  when:
    - ( postgresql_backups is defined )
    - ( postgresql_backups | length > 0 )
  tags:
    - postgresql
...
