---
- name: Generate a PostgreSQL password and write it to .pgpass
  block:

    - name: Include tasks to set the postgresql_postgres_home variable
      ansible.builtin.include_tasks: home.yml

    - name: PostgreSQL password generated
      ansible.builtin.command: "pwgen -n {{ 24 | random(14) }} 1"
      check_mode: false
      changed_when: false
      register: postgresql_pwgen
      no_log: true

    - name: Set a fact for the PostgreSQL password
      ansible.builtin.set_fact:
        postgresql_password: "{{ postgresql_pwgen.stdout | trim }}"
        postgresql_pgpass_line: "{{ postgresql_host | default('localhost') }}:{{ postgresql_port | default('5432') }}:{{ postgresql_db }}:{{ postgresql_user }}"
      no_log: true

    - name: Password written to /.pgpass
      ansible.builtin.lineinfile:
        path: "{{ postgresql_postgres_home }}/.pgpass"
        line: "{{ postgresql_pgpass_line }}:{{ postgresql_password }}"
        state: present
        create: true
        owner: "{{ postgresql_superuser | default('postgres') }}"
        group: "{{ postgresql_superuser | default('postgres') }}"
        mode: 0600
      no_log: true

  tags:
    - postgresql
...
