---
- name: Read the PostgreSQL password from the .pgpass file
  block:

    - name: Include tasks to set the postgresql_postgres_home variable
      ansible.builtin.include_tasks: home.yml
      when: >-
        ( postgresql_postgres_home is not defined ) or
        ( postgresql_postgres_home | length == 0 )

    - name: Slurp .pgpass
      ansible.builtin.slurp:
        src: "{{ postgresql_postgres_home }}/.pgpass"
      register: postgresql_pgpass_b64encoded
      no_log: "{% if ansible_verbosity < 2 %}true{% else %}false{% endif %}"

    - name: Set an array for the lines in .pgpass and a variable for the line to match
      ansible.builtin.set_fact:
        postgresql_pgpass_line: "{{ postgresql_host }}:{{ postgresql_port }}:{{ postgresql_db }}:{{ postgresql_user }}"
        postgresql_pgpass_lines: "{{ ( postgresql_pgpass_b64encoded['content'] | b64decode | trim ).split('\n') }}"
      no_log: "{% if ansible_verbosity < 2 %}true{% else %}false{% endif %}"

    - name: Debug postgresql_pgpass_lines
      ansible.builtin.debug:
        var: postgresql_pgpass_lines
        verbosity: 3

    - name: Read the PostgreSQL user password line from the postgresql_pgpass_lines array and split it into another array saving the 5th value
      ansible.builtin.set_fact:
        postgresql_password: "{{ line.split(':')[4] }}"
      when: postgresql_pgpass_line in line
      loop: "{{ postgresql_pgpass_lines }}"
      loop_control:
        loop_var: line
      no_log: "{% if ansible_verbosity < 2 %}true{% else %}false{% endif %}"

    # TODO Check that the password works and if it doesn't delete the line
    # and set postgresql_password back to an empty string

  tags:
    - postgresql
...
