---
- name: Generate a PostgreSQL password and write it to .pgpass
  block:

    - name: Include tasks to set the postgresql_postgres_home variable
      include_tasks: home.yml

    - name: PostgreSQL password generated
      command: pwgen -n 20 1
      register: postgresql_pwgen
      check_mode: false
      no_log: true

    - name: Set a fact for the PostgreSQL password
      set_fact:
        postgresql_password: "{{ postgresql_pwgen.stdout | trim }}"
        postgresql_pgpass_line: "{{ postgresql_host }}:{{ postgresql_port }}:{{ postgresql_db }}:{{ postgresql_user }}"
      no_log: true

    - name: "Password written to {{ postgresql_postgres_home }}/.pgpass"
      lineinfile:
        path: "{{ postgresql_postgres_home }}/.pgpass"
        line: "{{ postgresql_pgpass_line }}:{{ postgresql_password }}"
        state: present
        create: true
        owner: postgres
        group: postgres
        mode: 0600
      no_log: true

  tags:
    - postgresql
...
